import {
  ArrowLeft,
  Bell,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CircleX,
  Clock,
  CreditCard,
  Eye,
  EyeOff,
  House,
  Info,
  LogOut,
  MapPin,
  Minus,
  Pencil,
  Plus,
  QrCode,
  RefreshCw,
  Search,
  Settings,
  Trash,
  TriangleAlert,
  User,
  Users,
  WifiOff,
  X,
  type LucideIcon,
} from 'lucide-react-native';

import type { IconName } from './Icon.types';

// Lista explícita (y no `import * as`) para que solo entren los iconos que la app usa.
export const ICON_REGISTRY: Readonly<Record<IconName, LucideIcon>> = {
  check: Check,
  close: X,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  arrowLeft: ArrowLeft,
  plus: Plus,
  minus: Minus,
  eye: Eye,
  eyeOff: EyeOff,
  search: Search,
  calendar: Calendar,
  clock: Clock,
  user: User,
  users: Users,
  bell: Bell,
  settings: Settings,
  home: House,
  wifiOff: WifiOff,
  alertTriangle: TriangleAlert,
  info: Info,
  checkCircle: CircleCheck,
  xCircle: CircleX,
  refresh: RefreshCw,
  qrCode: QrCode,
  logOut: LogOut,
  camera: Camera,
  trash: Trash,
  edit: Pencil,
  mapPin: MapPin,
  creditCard: CreditCard,
};
